name: all_projects_flutter_dart3a
description: All tekartik public flutter projects

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ^3.9.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  dev_build: ">=1.1.2"
  archive: ">=4.0.5"
  dev_flutter_test:
    git:
      url: https://github.com/tekartik/dev_flutter_test
      ref: dart3a
      path: dev_flutter_test
  tekartik_app_flutter_sembast:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart3a
      path: app_sembast
    version: ">=0.5.1"
  tekartik_app_prefs:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart3a
      path: app_prefs
    version: ">=0.4.2"
  tekartik_app_pick_crop_image_flutter:
    git:
      url: https://github.com/tekartik/app_image.dart
      ref: dart3a
      path: packages/app_pick_crop_image_flutter
    version: ">=0.2.0"
  tekartik_notepad_sqflite_app:
    git:
      url: https://github.com/alextekartik/flutter_app_example
      path: notepad_sqflite
      ref: dart3a
    version: '>=0.1.0'
  tekartik_notepad_sembast_app:
    git:
      url: https://github.com/alextekartik/flutter_app_example
      path: notepad_sembast
      ref: dart3a
    version: '>=0.1.0'
  tekartik_notepad_idb_app:
    git:
      url: https://github.com/alextekartik/flutter_app_example
      path: notepad_idb
      ref: dart3a
    version: '>=0.1.0'
  tekartik_notepad_sdb_app:
    git:
      url: https://github.com/alextekartik/flutter_app_example
      ref: dart3a
      path: notepad_sdb
  tekartik_qrscan_flutter_web:
    git:
      url: https://github.com/tekartik/app_camera.dart
      path: qrscan_flutter_web
      ref: dart3a
    version: '>=0.1.0'
  sembast_cloud_firestore_type_adapters:
    git:
      url: https://github.com/tekartik/sembast_flutter_more.dart
      path: cloud_firestore_type_adapters
      ref: dart3a
    version: '>=0.1.0'
  # Some apps
  tkcms_admin_app:
    git:
      url: https://github.com/tekartikprj/tkcms.git
      ref: dart3a
      path: flutter_packages/tkcms_admin_app
  sembast_db_explorer:
    git:
      url: https://github.com/tekartik/sembast_flutter_more.dart
      path: sembast_db_explorer
      ref: dart3a
    version: '>=0.1.0'
  tekartik_app_flutter_widget:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart3a
      path: app_widget
    version: ">=0.2.3"
  # App
  tekaly_firestore_explorer_test_app:
    git:
      url: https://github.com/tekartikprj/tekaly
      ref: dart3a
      path: test/firestore_explorer_test_app
    version: ">=1.0.0+1"
  tekartik_firebase_firestore_flutter:
    git:
      url: https://github.com/tekartik/firebase_flutter
      path: firestore_flutter
      ref: dart3a
  tekartik_firebase_auth_flutter:
    git:
      url: https://github.com/tekartik/firebase_flutter
      path: auth_flutter
      ref: dart3a
  tekartik_firebase_flutter:
    git:
      url: https://github.com/tekartik/firebase_flutter
      path: firebase_flutter
      ref: dart3a
  tekartik_firebase_storage_flutter:
    git:
      url: https://github.com/tekartik/firebase_flutter
      path: storage_flutter
      ref: dart3a
  tekartik_firebase_functions_call_flutter:
    git:
      url: https://github.com/tekartik/firebase_flutter
      ref: dart3a
      path: functions_call_flutter
  tekartik_test_menu_flutter:
    git:
      url: https://github.com/tekartik/test_menu_flutter
      ref: dart3a
      path: test_menu_flutter
  tekartik_firebase_ui_auth:
    git:
      url: https://github.com/tekartik/firebase_ui.dart
      path: packages/firebase_ui_auth
      ref: dart3a
  tekartik_firebase_flutter_ui_auth:
    git:
      url: https://github.com/tekartik/firebase_ui.dart
      path: packages/firebase_flutter_ui_auth
      ref: dart3a
  tekaly_file_download:
    git:
      url: https://github.com/tekartikprj/tekaly
      path: flutter_packages/file_download
      ref: dart3a
  tekaly_firestore_explorer:
    git:
      url: https://github.com/tekartikprj/tekaly
      path: flutter_packages/firestore_explorer
      ref: dart3a
  tekartik_bluetooth_flutter:
    git:
      url: https://github.com/tekartik/bluetooth.dart
      ref: dart3a
      path: bluetooth_flutter
    version: ">=0.5.0"
  sqflite_example_common:
    git:
      url: https://github.com/tekartik/sqflite
      ref: dart3a
      path: packages_flutter/sqflite_example_common
  tekartik_app_rx_bloc_flutter:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart3a
      path: app_rx_bloc
  tekartik_app_flutter_fs:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart3a
      path: app_fs
  festenao_base_app:
    git:
      url: https://github.com/tekaly/festenao
      ref: dart3a
      path: packages_flutter/festenao_base_app
  festenao_icon:
    git:
      url: https://github.com/tekaly/festenao
      ref: dart3a
      path: packages_flutter/festenao_icon
  festenao_theme:
    git:
      url: https://github.com/tekaly/festenao
      ref: dart3a
      path: packages_flutter/festenao_theme
  festenao_markdown:
    git:
      url: https://github.com/tekaly/festenao
      ref: dart3a
      path: packages_flutter/festenao_markdown
  festenao_common_flutter:
    git:
      url: https://github.com/tekaly/festenao
      ref: dart3a
      path: packages_flutter/festenao_common_flutter
  festenao_youtube_player:
    git:
      url: https://github.com/tekaly/festenao
      ref: dart3a
      path: packages_flutter/festenao_youtube_player

  all_projects_dart3a:
    path: ../all_projects_dart3a

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ">=1.0.8"
  collection: '>=1.18.0'
  process_run: ">=1.2.1+1"
  tekartik_firebase_vertex_ai_flutter:
    git:
      url: https://github.com/tekartik/firebase_flutter
      ref: dart3a
      path: vertex_ai_flutter
  tekartik_app_flutter_utils_test_app:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart3a
      path: example/test_app
  tekartik_midi_device_flutter_command:
    git:
      url: https://github.com/tekartikprj/midi_device
      path: packages/midi_device_flutter_command
      ref: dart3a
  tekartik_app_url_launcher_flutter:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart3a
      path: app_url_launcher
    version: '>=0.0.1'
dependency_overrides:
  synchronized:
    git:
      url: https://github.com/tekartik/synchronized.dart
      path: synchronized
      ref: dart3a
  sembast:
    git:
      url: https://github.com/tekartik/sembast.dart
      path: sembast
      ref: dart3a
  sembast_web:
    git:
      url: https://github.com/tekartik/sembast.dart
      path: sembast_web
      ref: dart3a
  sqflite:
    git:
      url: https://github.com/tekartik/sqflite
      path: sqflite
      ref: dart3a
  sqflite_common:
    git:
      url: https://github.com/tekartik/sqflite
      path: sqflite_common
      ref: dart3a
  sqflite_common_ffi:
    git:
      url: https://github.com/tekartik/sqflite
      path: sqflite_common_ffi
      ref: dart3a
  sqflite_common_ffi_async:
    git:
      url: https://github.com/tekartik/sqflite
      path: packages/sqflite_common_ffi_async
      ref: dart3a
  sqflite_common_ffi_web:
    git:
      url: https://github.com/tekartik/sqflite
      path: packages_web/sqflite_common_ffi_web
      ref: dart3a
  pubglobalupdate:
    git:
      url: https://github.com/tekartik/pubglobalupdate.dart
      ref: dart3a
  idb_shim:
    git:
      url: https://github.com/tekartik/idb_shim.dart
      path: idb_shim
      ref: dart3a
  idb_sqflite:
    git:
      url: https://github.com/tekartik/idb_sqflite
      path: idb_sqflite
      ref: dart3a
  dev_test:
    git:
      url: https://github.com/tekartik/dev_test.dart
      path: dev_test
      ref: dart3a
  dev_build:
    git:
      url: https://github.com/tekartik/dev_test.dart
      path: dev_build
      ref: dart3a
  cv:
    git:
      url: https://github.com/tekartik/cv.dart
      path: packages/cv
      ref: dart3a
  process_run:
    git:
      url: https://github.com/tekartik/process_run.dart
      path: packages/process_run
      ref: dart3a
  fs_shim:
    git:
      url: https://github.com/tekartik/fs_shim.dart
      path: fs
      ref: dart3a
  tekartik_app_flutter_common_web_utils:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart3a
      path: app_common_web
  festenao_admin_base_app:
    git:
      url: https://github.com/tekaly/festenao
      ref: dart3a
      path: packages_flutter/festenao_admin_base_app
  festenao_audio_player:
    git:
      url: https://github.com/tekaly/festenao
      path: packages_flutter/festenao_audio_player
      ref: dart3a
    version: '>=0.2.0'
  festenao_firebase_flutter:
    git:
      url: https://github.com/tekaly/festenao
      ref: dart3a
      path: packages_flutter/festenao_firebase_flutter
  tekartik_kiosk:
    git:
      url: https://github.com/tekartikprj/android_tools
      path: packages/kiosk
      ref: dart3a
  tekartik_kiosk_app:
    git:
      url: https://github.com/tekartikprj/android_tools
      path: packages/kiosk_app
      ref: dart3a
  festenao_media_base_app:
    git:
      url: https://github.com/tekaly/festenao
      ref: dart3a
      path: packages_flutter/festenao_media_base_app
  playlr_audio_recorder:
    git:
      url: https://github.com/tekaly/playlr.git
      path: packages_flutter/playlr_audio_recorder
      ref: dart3a
  playlr_audio_player_blue_fire:
    git:
      url: https://github.com/tekaly/playlr.git
      path: packages_flutter/playlr_audio_player_blue_fire
      ref: dart3a
    version: '>=0.0.1'
  playlr_audio_player_just_audio:
    git:
      url: https://github.com/tekaly/playlr.git
      ref: dart3a
      path: packages_flutter/playlr_audio_player_just_audio
  a2ktik_kar:
    git:
      url: https://github.com/a2ktik/a2ktikcommonpublic
      path: packages/a2ktik_kar
      ref: dart3a

dev_dependencies:
  # needed for firebase_auth_jwt
  corsac_jwt: ">=2.0.1"
  path: ">=1.9.0"
  intl: ">=0.19.0"
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ">=5.0.0"
  tekartik_prj_tktools:
    git:
      url: https://github.com/tekartikprj/tktools.git
      ref: dart3a
      path: packages/prj_tktools

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
