name: all_projects_dart2_3
description: All dart packages
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  tekartik_firebase_firestore_rest:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore_rest
      ref: dart2_3
    version: '>=0.8.0'
  tekartik_firebase_storage_rest:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage_rest
      ref: dart2_3
    version: '>=0.8.0'
  tekartik_app_image_web:
    git:
      url: https://github.com/tekartik/app_image.dart
      path: packages/app_image_web
      ref: dart2_3
    version: '>=0.1.0'
  tekartik_tone_js:
    git:
      url: https://github.com/tekartik/tone_js.dart
      ref: dart2_3
    version: '>=0.1.1'
  tekartik_fs_test:
    git:
      url: https://github.com/tekartik/fs_shim.dart
      path: fs_test
      ref: dart2_3
    version: '>=0.1.0'
  sqflite_common_test:
    git:
      url: https://github.com/tekartik/sqflite
      ref: dart2_3
      path: sqflite_common_test
    version: '>=0.3.0'
  sqflite_common_porter:
    git:
      url: https://github.com/tekartik/sqflite_more
      ref: dart2_3
      path: sqflite_common_porter
    version: '>=0.2.0'
  tekartik_build_utils:
    git:
      url: https://github.com/tekartik/build_utils.dart
      ref: dart2_3
    version: '>=0.7.9'
  tekartik_bluetooth:
    git:
      url: https://github.com/tekartik/bluetooth.dart
      path: bluetooth
      ref: dart2_3
  tekartik_http_io:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_io
      ref: dart2_3
    version: '>=0.2.0+2'
  tekartik_build_menu_flutter:
    git:
      url: https://github.com/tekartik/build_flutter.dart
      ref: dart2_3
      path: packages/build_menu_flutter
    version: '>=0.1.0'
  tekartik_bluetooth_bluez:
    git:
      url: https://github.com/tekartik/bluetooth.dart
      path: bluetooth_bluez
      ref: dart2_3
    version: '>=0.0.1'
  tekartik_midi:
    git:
      url: https://github.com/tekartik/midi.dart
      ref: dart2_3
  tekartik_mustache_cli:
    git:
      url: https://github.com/tekartik/mustache.dart
      path: mustache_cli
      ref: dart2_3
    version: '>=0.2.2'
  idb_test:
    git:
      url: https://github.com/tekartik/idb_shim.dart
      path: idb_test
      ref: dart2_3
    version: '>=0.3.3'
  idb_sqflite_common_test:
    git:
      url: https://github.com/tekartik/idb_sqflite
      path: idb_sqflite_common_test
      ref: dart2_3
    version: '>=0.2.0'
  sembast_sqflite_common_test:
    git:
      url: https://github.com/tekartik/sembast_sqflite
      path: sembast_sqflite_common_test
      ref: dart2_3
    version: '>=0.1.0'
  tekartik_firebase_functions_io:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: firebase_functions_io
      ref: dart2_3
    version: '>=0.2.1'
  tekartik_prefs_sembast:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs_sembast
      ref: dart2_3
    version: '>=0.1.0'
  tekartik_app_io_prefs:
    git:
      url: https://github.com/tekartik/app_io_utils.dart
      ref: dart2_3
      path: packages/app_prefs
    version: '>=0.1.1'
  tekartik_app_io_launcher:
    git:
      url: https://github.com/tekartik/app_io_utils.dart
      ref: dart2_3
      path: packages/app_launcher
    version: '>=0.1.1'
  tekartik_app_io_platform:
    git:
      url: https://github.com/tekartik/app_io_utils.dart
      ref: dart2_3
      path: packages/app_platform
    version: '>=0.3.1'
  tekartik_app_secure_env:
    git:
      url: https://github.com/tekartik/app_io_utils.dart
      ref: dart2_3
      path: packages/app_secure_env
    version: '>=0.1.0'
  tekartik_app_io_sembast:
    git:
      url: https://github.com/tekartik/app_io_utils.dart
      ref: dart2_3
      path: packages/app_sembast
    version: '>=0.1.0'
  tekartik_app_io_sqflite:
    git:
      url: https://github.com/tekartik/app_io_utils.dart
      ref: dart2_3
      path: packages/app_sqflite
    version: '>=0.2.0'
  tekartik_app_io_zip:
    git:
      url: https://github.com/tekartik/app_io_utils.dart
      ref: dart2_3
      path: packages/app_zip
    version: '>=0.2.0'
  tekartik_rpc:
    git:
      url: https://github.com/tekartik/rpc.dart
      ref: dart2_3
      path: packages/rpc
    version: '>=0.1.0'
  tekartik_mailjet:
    git:
      url: https://github.com/alextekartik/http_apis.dart
      path: packages/mailjet
      ref: dart2_3
    version: '>=0.1.0'
  tekartik_pubtest:
    git:
      url: https://github.com/tekartik/pubtest.dart
      ref: dart2_3
    version: '>=0.7.0'
_tmp:
  tekartik_firebase_firestore_sim_io:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_sim_io
      ref: dart2_3
    version: '>=0.8.0'

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
