name: all_projects_dart3a
description: All dart packages
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  tekartik_firebase_firestore_rest:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore_rest
      ref: dart3a
    version: '>=0.8.0'
  tekartik_firebase_storage_rest:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage_rest
      ref: dart3a
    version: '>=0.8.0'
  tekartik_app_image_web:
    git:
      url: https://github.com/tekartik/app_image.dart
      path: packages/app_image_web
      ref: dart3a
    version: '>=0.1.0'
  tekartik_tone_js:
    git:
      url: https://github.com/tekartik/tone_js.dart
      ref: dart3a
    version: '>=0.1.1'
  tekartik_fs_test:
    git:
      url: https://github.com/tekartik/fs_shim.dart
      path: fs_test
      ref: dart3a
    version: '>=0.1.0'
  sqflite_common_test:
    git:
      url: https://github.com/tekartik/sqflite
      ref: dart3a
      path: sqflite_common_test
    version: '>=0.3.0'
  sqflite_common_porter:
    git:
      url: https://github.com/tekartik/sqflite_more
      ref: dart3a
      path: sqflite_common_porter
    version: '>=0.2.0'
  tekartik_build_utils:
    git:
      url: https://github.com/tekartik/build_utils.dart
      ref: dart3a
    version: '>=0.7.9'
  tekartik_bluetooth:
    git:
      url: https://github.com/tekartik/bluetooth.dart
      path: bluetooth
      ref: dart3a
  tekartik_http_io:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_io
      ref: dart3a
    version: '>=0.2.0+2'
  tekartik_build_menu_flutter:
    git:
      url: https://github.com/tekartik/build_flutter.dart
      ref: dart3a
      path: packages/build_menu_flutter
    version: '>=0.1.0'
  tekartik_bluetooth_bluez:
    git:
      url: https://github.com/tekartik/bluetooth.dart
      path: bluetooth_bluez
      ref: dart3a
    version: '>=0.0.1'
  tekartik_midi:
    git:
      url: https://github.com/tekartik/midi.dart
      ref: dart3a
  tekartik_mustache_cli:
    git:
      url: https://github.com/tekartik/mustache.dart
      path: mustache_cli
      ref: dart3a
    version: '>=0.2.2'
  idb_test:
    git:
      url: https://github.com/tekartik/idb_shim.dart
      path: idb_test
      ref: dart3a
    version: '>=0.3.3'
  idb_sqflite_common_test:
    git:
      url: https://github.com/tekartik/idb_sqflite
      path: idb_sqflite_common_test
      ref: dart3a
    version: '>=0.2.0'
  tekartik_aliyun_tablestore_node:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: node/tablestore_node
      ref: dart3a
    version: '>=0.1.0'
  tekartik_aliyun_oss_universal:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: common/oss_universal
      ref: dart3a
    version: '>=0.1.0'
  tekartik_aliyun_fc_universal:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: common/fc_universal
      ref: dart3a
    version: '>=0.1.0'
  tekartik_aliyun_tablestore_universal:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: common/tablestore_universal
      ref: dart3a
    version: '>=0.1.0'
  sembast_sqflite_common_test:
    git:
      url: https://github.com/tekartik/sembast_sqflite
      path: sembast_sqflite_common_test
      ref: dart3a
    version: '>=0.1.0'

_tmp:
  tekartik_firebase_firestore_sim_io:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_sim_io
      ref: dart3a
    version: '>=0.8.0'

dev_dependencies:
  lints: '>=1.0.0'
  test: '>=1.16.0'